import React from 'react';
import { motion } from 'framer-motion';
import { Download } from 'lucide-react';

const formatSectionTitle = (key) => {
  return key
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\b\w/g, (c) => c.toUpperCase());
};

export const ExportButton = ({ note }) => {
  const handleExport = () => {
    if (!note) return;

    // Support both old shape and new dynamic sections shape
    const sections = note.sections
      ? note.sections
      : {
          ...(note.summary?.length       ? { summary: note.summary }             : {}),
          ...(note.key_decisions?.length ? { key_decisions: note.key_decisions } : {}),
          ...(note.action_items?.length  ? { action_items: note.action_items }   : {}),
        };

    const typeLabel = note.type ? `**Type:** ${note.type}\n\n` : '';

    const sectionsMarkdown = Object.entries(sections)
      .filter(([, items]) => Array.isArray(items) && items.length > 0)
      .map(([key, items]) =>
        `## ${formatSectionTitle(key)}\n${items.map((s) => `- ${s}`).join('\n')}`
      )
      .join('\n\n');

    const tagsMarkdown = note.tags?.length
      ? `\n\n## Tags\n${note.tags.map((t) => `\`${t}\``).join(' ')}`
      : '';

    const md = `# ${note.title}\n\n${typeLabel}${sectionsMarkdown}${tagsMarkdown}\n\n---\n*Generated by Lumina Note*\n`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${note.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <motion.button
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      onClick={handleExport}
      className="flex items-center gap-2 px-5 py-2.5 rounded-full text-sm font-medium bg-white/5 hover:bg-white/10 text-zinc-300 border border-white/10 transition-colors duration-200"
      data-testid="export-btn"
    >
      <Download size={14} />
      Export .md
    </motion.button>
  );
};