/** Shared note-shape helpers, so the output, history and export views agree. */

const LANGUAGE_NAMES = {
  en: 'English', fr: 'Français', es: 'Español', de: 'Deutsch', it: 'Italiano',
  pt: 'Português', nl: 'Nederlands', ar: 'العربية', zh: '中文', ja: '日本語',
  ko: '한국어', ru: 'Русский', hi: 'हिन्दी', tr: 'Türkçe', pl: 'Polski', sv: 'Svenska',
};

export const languageName = (code) => LANGUAGE_NAMES[code] || '';

/** Fall back to a title-cased key when the model gave us no localized label. */
export const titleFromKey = (key) =>
  String(key)
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\b\w/g, (character) => character.toUpperCase());

export const sectionLabel = (key, labels) => {
  const label = labels?.[key];
  return typeof label === 'string' && label.trim() ? label.trim() : titleFromKey(key);
};

/**
 * Sections for a note in render order, tolerating notes saved before the
 * dynamic-sections rewrite (which used fixed summary/key_decisions/action_items).
 */
export const sectionEntries = (note) => {
  if (!note) return [];

  const sections =
    note.sections && Object.keys(note.sections).length > 0
      ? note.sections
      : {
          ...(note.summary?.length ? { summary: note.summary } : {}),
          ...(note.key_decisions?.length ? { key_decisions: note.key_decisions } : {}),
          ...(note.action_items?.length ? { action_items: note.action_items } : {}),
        };

  return Object.entries(sections).filter(
    ([, items]) => Array.isArray(items) && items.length > 0,
  );
};

export const bulletCount = (note) =>
  sectionEntries(note).reduce((total, [, items]) => total + items.length, 0);

export const noteToMarkdown = (note) => {
  const entries = sectionEntries(note);
  const meta = [
    note.type ? `**Type:** ${note.type}` : '',
    note.language && note.language !== 'auto'
      ? `**Language:** ${languageName(note.language) || note.language}`
      : '',
    note.created_at ? `**Date:** ${new Date(note.created_at).toLocaleString()}` : '',
  ].filter(Boolean);

  const body = entries
    .map(
      ([key, items]) =>
        `## ${sectionLabel(key, note.labels)}\n${items.map((item) => `- ${item}`).join('\n')}`,
    )
    .join('\n\n');

  const tags = note.tags?.length
    ? `\n\n## Tags\n${note.tags.map((tag) => `\`${tag}\``).join(' ')}`
    : '';

  const transcript = note.raw_transcript
    ? `\n\n## Transcript\n\n${note.raw_transcript.trim()}`
    : '';

  return [
    `# ${note.title || 'Untitled note'}`,
    meta.join('  \n'),
    body,
    tags.trim(),
    transcript.trim(),
    '---\n*Generated by Lumina Note*',
  ]
    .filter(Boolean)
    .join('\n\n')
    .concat('\n');
};

export const downloadMarkdown = (note) => {
  const markdown = noteToMarkdown(note);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const slug =
    (note.title || 'note')
      .toLowerCase()
      .replace(/[^\p{L}\p{N}]+/gu, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'note';

  link.href = url;
  link.download = `${slug}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Revoking immediately can cancel the download in Safari.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};

/**
 * Split a bullet into runs of plain, bold, italic and code text.
 *
 * Models write inline Markdown whether or not they were asked to - a stray
 * **like this** rendered as literal asterisks, which looked like a bug because
 * it was one. Parsing it means emphasis either renders properly or, for a
 * pattern we do not handle, survives as the characters that were written.
 *
 * Deliberately tiny: bullets are one sentence, so there is no block structure
 * to parse and no reason to pull in a Markdown library for it.
 *
 * LaTeX comes first, between $...$ or $$...$$, so the underscores and stars a
 * formula is full of are never read as emphasis. A dollar that opens or
 * closes against a space ("50 $") is a price, not maths.
 */
const INLINE_PATTERN = /(\$\$[\s\S]+?\$\$|\$(?!\s)[^$\n]+?(?<!\s)\$|\*\*[^*\n]+\*\*|__[^_\n]+__|`[^`\n]+`|(?<![*\w])\*[^*\n]+\*(?!\w)|(?<![_\w])_[^_\n]+_(?!\w))/g;
const MATH_PATTERN = /(\$\$[\s\S]+?\$\$|\$(?!\s)[^$\n]+?(?<!\s)\$)/;

const isMath = (piece) => piece.length > 2 && piece.startsWith('$') && piece.endsWith('$');

const mathRun = (piece, key) => {
  const display = piece.startsWith('$$') && piece.length > 4;
  const tex = piece.slice(display ? 2 : 1, display ? -2 : -1).trim();
  return { key, text: piece, tex, math: true, display };
};

/** A bullet that is nothing but a displayed equation, which needs no bullet dot. */
export const isDisplayMath = (text) => typeof text === 'string' && /^\s*\$\$[\s\S]+\$\$\s*$/.test(text);

/** Text that is one inline formula and nothing else, such as a card's answer. */
export const isLoneFormula = (text) => typeof text === 'string' && /^\s*\$(?!\$)[^$]+\$\s*$/.test(text);

/** Plain text and LaTeX, for what sits inside a bold or italic run. */
export const mathParts = (text) =>
  String(text || '')
    .split(MATH_PATTERN)
    // split() puts what the pattern matched at the odd positions.
    .map((piece, index) => (index % 2 ? mathRun(piece, index) : { key: index, text: piece }))
    .filter((part) => part.text);

export const inlineRuns = (text) => {
  const source = typeof text === 'string' ? text : '';
  if (!source) return [];

  const runs = [];
  let index = 0;

  source.split(INLINE_PATTERN).forEach((piece, position) => {
    if (!piece) return;
    index += 1;
    // Only a stretch the pattern matched (odd positions) can be maths: plain
    // text that merely starts and ends with a dollar stays text.
    if (position % 2 && isMath(piece)) {
      runs.push(mathRun(piece, index));
    } else if (piece.startsWith('**') && piece.endsWith('**')) {
      runs.push({ key: index, text: piece.slice(2, -2), bold: true });
    } else if (piece.startsWith('__') && piece.endsWith('__')) {
      runs.push({ key: index, text: piece.slice(2, -2), bold: true });
    } else if (piece.startsWith('`') && piece.endsWith('`')) {
      runs.push({ key: index, text: piece.slice(1, -1), code: true });
    } else if (
      (piece.startsWith('*') && piece.endsWith('*')) ||
      (piece.startsWith('_') && piece.endsWith('_'))
    ) {
      runs.push({ key: index, text: piece.slice(1, -1), italic: true });
    } else {
      runs.push({ key: index, text: piece });
    }
  });

  return runs;
};

/**
 * A review question bullet ("Question ? → answer") as {question, answer}, or
 * null when it is not written that way and should show as a plain bullet.
 */
export const splitQuestion = (text) => {
  const found = /^(.+?)\s+(?:→|->|=>)\s+(.+)$/s.exec(typeof text === 'string' ? text : '');
  return found ? { question: found[1].trim(), answer: found[2].trim() } : null;
};

/** The same text with its formatting removed, for previews and plain contexts. */
export const stripInline = (text) =>
  inlineRuns(text)
    .map((run) => run.text)
    .join('');

// ── Library and revision helpers ────────────────────────────────────────────

/** What the note types are called in the library filter. */
export const TYPE_LABELS = {
  LECTURE: 'Lectures',
  MEETING: 'Meetings',
  INTERVIEW: 'Interviews',
  BRAINSTORM: 'Brainstorms',
  OTHER: 'Other',
};

/** One line to recognise a note by in a list: its overview, else its first point. */
export const notePreview = (note) => {
  const sections = note?.sections || {};
  const lead = ['overview', 'summary', 'key_takeaways']
    .map((key) => (Array.isArray(sections[key]) ? sections[key][0] : ''))
    .find(Boolean);
  return stripInline(lead || sectionEntries(note)[0]?.[1]?.[0] || '');
};

/** Points to read and questions to revise from, for the list's meta line. */
export const noteCounts = (note) => {
  const questions = note?.sections?.review_questions?.length || 0;
  return { points: bulletCount(note) - questions, questions, cards: buildDeck(note).length };
};

const startOfDay = (date) => new Date(date.getFullYear(), date.getMonth(), date.getDate());

/**
 * Notes grouped the way you look for them: today, yesterday, this week, then
 * by month. Expects them newest first, as the API returns them.
 */
export const groupByDate = (notes, now = new Date()) => {
  const today = startOfDay(now).getTime();
  const DAY = 86400000;
  const groups = [];
  const labelFor = (note) => {
    const created = new Date(note.created_at);
    if (Number.isNaN(created.getTime())) return 'Earlier';
    const day = startOfDay(created).getTime();
    if (day >= today) return 'Today';
    if (day >= today - DAY) return 'Yesterday';
    if (day >= today - 6 * DAY) return 'This week';
    return created.toLocaleDateString(undefined, { month: 'long', year: 'numeric' });
  };
  notes.forEach((note) => {
    const label = labelFor(note);
    const last = groups[groups.length - 1];
    if (last && last.label === label) last.notes.push(note);
    else groups.push({ label, notes: [note] });
  });
  return groups;
};

// "**Term** : explanation", with a colon, dash or en/em dash after the term.
const TERM_LEAD = /^\*\*(.+?)\*\*\s*[:—–-]\s*(.+)$/s;

/**
 * Flashcards for a note: its review questions, then every defined term, then
 * every explained concept. All of it comes from the note itself, so revising
 * never tests anything the lecture did not say.
 */
export const buildDeck = (note) => {
  const sections = note?.sections || {};
  const cards = [];
  (sections.review_questions || []).forEach((text, index) => {
    const pair = splitQuestion(text);
    if (pair) cards.push({ id: `q${index}`, kind: 'question', front: pair.question, back: pair.answer });
  });
  ['definitions', 'key_concepts', 'methods'].forEach((key) => {
    (sections[key] || []).forEach((text, index) => {
      const found = TERM_LEAD.exec(typeof text === 'string' ? text.trim() : '');
      if (found) cards.push({ id: `${key}${index}`, kind: key, front: found[1].trim(), back: found[2].trim() });
    });
  });
  return cards;
};
