/** Shared note-shape helpers, so the output, history and export views agree. */

const LANGUAGE_NAMES = {
  en: 'English', fr: 'Français', es: 'Español', de: 'Deutsch', it: 'Italiano',
  pt: 'Português', nl: 'Nederlands', ar: 'العربية', zh: '中文', ja: '日本語',
  ko: '한국어', ru: 'Русский', hi: 'हिन्दी', tr: 'Türkçe', pl: 'Polski', sv: 'Svenska',
};

export const languageName = (code) => LANGUAGE_NAMES[code] || '';

/** Fall back to a title-cased key when the model gave us no localized label. */
export const titleFromKey = (key) =>
  String(key)
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\b\w/g, (character) => character.toUpperCase());

export const sectionLabel = (key, labels) => {
  const label = labels?.[key];
  return typeof label === 'string' && label.trim() ? label.trim() : titleFromKey(key);
};

/**
 * Sections for a note in render order, tolerating notes saved before the
 * dynamic-sections rewrite (which used fixed summary/key_decisions/action_items).
 */
export const sectionEntries = (note) => {
  if (!note) return [];

  const sections =
    note.sections && Object.keys(note.sections).length > 0
      ? note.sections
      : {
          ...(note.summary?.length ? { summary: note.summary } : {}),
          ...(note.key_decisions?.length ? { key_decisions: note.key_decisions } : {}),
          ...(note.action_items?.length ? { action_items: note.action_items } : {}),
        };

  return Object.entries(sections).filter(
    ([, items]) => Array.isArray(items) && items.length > 0,
  );
};

export const bulletCount = (note) =>
  sectionEntries(note).reduce((total, [, items]) => total + items.length, 0);

export const noteToMarkdown = (note) => {
  const entries = sectionEntries(note);
  const meta = [
    note.type ? `**Type:** ${note.type}` : '',
    note.language && note.language !== 'auto'
      ? `**Language:** ${languageName(note.language) || note.language}`
      : '',
    note.created_at ? `**Date:** ${new Date(note.created_at).toLocaleString()}` : '',
  ].filter(Boolean);

  const body = entries
    .map(
      ([key, items]) =>
        `## ${sectionLabel(key, note.labels)}\n${items.map((item) => `- ${item}`).join('\n')}`,
    )
    .join('\n\n');

  const tags = note.tags?.length
    ? `\n\n## Tags\n${note.tags.map((tag) => `\`${tag}\``).join(' ')}`
    : '';

  const transcript = note.raw_transcript
    ? `\n\n## Transcript\n\n${note.raw_transcript.trim()}`
    : '';

  return [
    `# ${note.title || 'Untitled note'}`,
    meta.join('  \n'),
    body,
    tags.trim(),
    transcript.trim(),
    '---\n*Generated by Lumina Note*',
  ]
    .filter(Boolean)
    .join('\n\n')
    .concat('\n');
};

export const downloadMarkdown = (note) => {
  const markdown = noteToMarkdown(note);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const slug =
    (note.title || 'note')
      .toLowerCase()
      .replace(/[^\p{L}\p{N}]+/gu, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'note';

  link.href = url;
  link.download = `${slug}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  // Revoking immediately can cancel the download in Safari.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
};
